### ISSUE TITLE
Why are you folks only decompiling the newer Zelda games?

### ISSUE THREAD

**Issue by JTMaher2** [zeldaret/website#79]
As an avid player of the Zelda games, I find it odd that the oldest one you are de-compiling is Ocarina of Time. I have so many good memories of playing the earlier Zeldas, such as Link's Awakening and A Link to the Past. It would be great if I could play them on a 4K UHD PC monitor with a HD texture pack. I know basic Assembly language programming, so I would be totally willing to help you folks accomplish this task.

P.S. Sorry if this is the wrong place to submit this issue. I know it's not about a problem with your website. If you want to close it, feel free to do so.

**Comment by AngheloAlf** [comment]
The decompilation process consists on reverse engineer a program (in this case the games) into the programming language the program was originally written on (usually C or C++). This only makes sense for programs that actually were "compilated" as opposed to just "assembled". Assembling code is a minor step compared to a full compilation process, and it is usually a lot more literal/automatable in comparison (I'm not trying to imply that this is simple either).

Currently the projects on this organization are matching decompilation projects, which means writing code on the original programming language that compiles exactly to the original binary. Because of this you can't, for example, write C code that would compile to a matching binary of an assembled-only game.

Older zelda games, like the SNES, NES, and GB ones were not written in a compilable language, they were written in pure assembly, so we can't decompile it. But, as far as I know there are disassembly projects at least a few of those games. You may want to take a look at those. Each architecture has its own assembly language, so a disassembly project for any of these games requires a deep understanding of the corresponding platform.

Neither the projects on this organization nor the disassembly projects of those older zelda games aim to port those games to a different platform from the original platform. Other groups of people may want to take the decompiled code as an starting point for their ports, but again this is not the goal of any of these projects.

**Comment by Mastergatto** [comment]
Nevertheless, this doesn't rule out any reimplementation or recreation in C (or any other language) of those assembly-only games. This doesn't mean they will match 1:1 to the original binary, just that they try to match the logic and other parts of the game.
In case of ALTTP, there's one organization (not zeldaret) that attempts to recreate it in C language: https://github.com/snesrev/zelda3

(I apologize, I just wanted to add this information to the reply above)
